filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/*.log
    
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]