---
- name: copy docker-compose file
  hosts: all
  tasks:
    - name: copy docker-compose file
      copy:
        src: ./docker_compose_crm.yml
        dest: ./
    - name:  docker-compose down
      command: docker-compose -f docker_compose_crm.yml down
    - name: run docker-compose file
      command: docker-compose -f docker_compose_crm.yml up -d